### ISSUE TITLE
React native vector icon not showing up

### ISSUE THREAD

**Issue by kenchoong** [kucira/nextjs-rnweb-rnelements#4]
Hey, nice work by the way. 
I just tested your repo.. But it seems the React-native-vector-icons cant show up any of them. I just dont know why. 

in index.js

```
import { Button, Text, Image } from 'react-native-elements';
import Icon from 'react-native-vector-icons/FontAwesome';

<View style={styles.container}>
     <Button
            icon={
                <Icon
                    name="arrow-right"
                    size={15}
                    color="white"
                />
            }
            title="button"
        />
</View>
```

All button it appear like this: 

![a12](https://user-images.githubusercontent.com/8010129/84590466-8b4b7a00-ae69-11ea-98a9-4f99970601e4.png)

Is there anything I missing out?

**Comment by kenchoong** [comment]
hey can you be so kind to give me some hint about this??

**Comment by kucira** [comment]
@kenchoong you can use this nextjs plugins for load the fonts
https://github.com/rohanray/next-fonts

after that this how to setup icons with react native elements https://react-native-elements.github.io/react-native-elements/docs/web_usage.html

i just update the repository, you can pull the new version with react native vector icons config.

**Comment by kenchoong** [comment]
wow..thanks a lot miss.. it finally works!!! Thank you very much.. 

Your latest repo update works.. Great works.. it help me a lot, cause I am total newbie in React. 

Really appreciate you help.
